spring.application.name=Notification System

# Base configuration
spring.datasource.url=jdbc:h2:mem:testdb-notification;MODE=MYSQL;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.transaction-type=RESOURCE_LOCAL
spring.h2.console.enabled=true
